# Generated by Django 5.0.3 on 2024-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='foto'),
        ),
    ]
