# Generated by Django 5.0.3 on 2024-03-13 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 12, 39, 59, 542407, tzinfo=datetime.timezone.utc), verbose_name='fecha de publicacion'),
        ),
    ]
